---
- name: install gpg
  apt:
    name: gnupg
    update_cache: yes    

- name: set login banner
  copy:
    src: issue
    dest: /etc/issue
    owner: root
    group: root
    mode: 0644

- name: set welcome banner
  copy:
    src: motd
    dest: /etc/motd
    owner: root
    group: root
    mode: 0644
