---
- name: install gpg
  apt:
    name: gnupg
    update_cache: yes    

- name: set login banner
  copy:
    src: issue
    dest: /etc/issue
    owner: root
    group: root
    mode: 0644

- name: set welcome banner
  copy:
    src: motd
    dest: /etc/motd
    owner: root
    group: root
    mode: 0644

- name: set authorized ssh keys
  template:
    src: authorized_keys.j2
    dest: /home/ansible/.ssh/authorized_keys
    owner: ansible
    group: ansible
    mode: '0644'

- name: set default DNS config
  template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf
    owner: root
    group: root
    mode: '0644'
