---
- name: add CRAN signing key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: E298A3A825C0D65DFD57CBB651716619E084DAB9
    state: present

- name: add CRAN repository
  apt_repository:
    repo: "deb https://cloud.r-project.org/bin/linux/ubuntu bionic-cran40/"
    state: present

- name: add RRutter repository
  apt_repository:
    repo: "ppa:marutter/rrutter4.0"
    state: present

- name: add CRAN dev repo
  apt_repository:
    repo: "ppa:c2d4u.team/c2d4u4.0+"
    state: present

- name: add poppler repo
  apt_repository:
    repo: "ppa:cran/poppler"
    state: present

- name: install common dependencies
  apt:
    pkg:
      - build-essential
      - python3-dev
      - python3-setuptools
      - python3
      - python3-apt
      - python3-dbus
      - python3-gi
      - git
      - curl
      - libxrender1
      - libfontconfig1
      - zip
      - unzip
      - htop
      - r-base
      - r-recommended
      - r-base-dev
      - littler
      - libpq-dev
      - libcurl4-openssl-dev
      - libssl-dev
      - libxml2-dev
      - libev-dev
      - software-properties-common
      - libpoppler-cpp-dev
      - libv8-dev
      - libmagick++-dev
    update_cache: yes

- name: create directory for admin scripts
  file:
    path: /srv/admin/scripts
    state: directory
    group: sudo
    mode: '0770'

- name: create directory for user scripts
  file:
    path: /srv/user/scripts
    state: directory
    group: sudo
    mode: '0777'

- name: copy add user script
  copy:
    src: ../../../../scripts/add_users.sh
    dest: /srv/admin/scripts
    group: sudo
    mode: '0550'

- name: copy nbgrader script
  copy:
    src: ../../../../scripts/enable_nbgrader.sh
    dest: /srv/admin/scripts
    group: sudo
    mode: '0550'

- name: copy research-drive script
  copy:
    src: ../../../../scripts/setup_research_drive_mount.sh
    dest: /srv/admin/scripts
    group: sudo
    mode: '0550'

- name: copy ssh-key script
  copy:
    src: ../../../../scripts/add_ssh_key.sh
    dest: /srv/user/scripts
    group: sudo
    mode: '0555'

- name: create datablock directory
  file:
    path: /mnt/datablock
    state: directory
    group: sudo
    mode: '0777'

- name: Create a xfs filesystem on /dev/vdb
  filesystem:
    fstype: xfs
    dev: /dev/vdb
  register: filesystem_created
  ignore_errors: yes

- name: mount data block
  mount:
    src: /dev/vdb
    path: /mnt/datablock
    fstype: xfs
    state: mounted
    opts: defaults,nofail
  ignore_errors: yes
  when: filesystem_created is succeeded

- name: link shared data directory to user home directories
  file:
    src: /mnt/datablock
    dest: /etc/skel/shared
    state: link
