---
- name: create base directory
  become: true
  file:
    path: /opt/Python
    state: directory
    group: sudo
    mode: '0755'

- name: install python
  become: true
  shell:
    cmd: "/opt/conda/miniconda/bin/conda create --quiet --yes \
      --prefix /opt/Python/{{ python_env_name }} \
      --channel conda-forge \
      python={{ python_version }}"
    creates: /opt/Python/{{ python_env_name }}
    
- name: install common python packages
  become: true
  pip:
    name:
      - ipykernel
      - virtualenv
    executable: /opt/Python/{{ python_env_name }}/bin/pip
