---
- name: create base directory
  file:
    path: /opt/Python
    state: directory
    group: sudo
    mode: '0755'

- name: download miniconda
  get_url:
    url: https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
    dest: /opt/Python/miniconda.sh 
    mode: '0755'
  register: download_conda

- name: install miniconda
  shell: /opt/Python/miniconda.sh -b -p /opt/Python/miniconda
  when: download_conda is changed

- name: install python
  shell: 
    cmd: "/opt/Python/miniconda/bin/conda create --quiet --yes \
      --prefix /opt/Python/{{ python_env_name }} \
      --channel conda-forge \
      python={{ python_version }}"
    creates: /opt/Python/{{ python_env_name }}
    
- name: install common python packages
  pip:
    name:
      - ipykernel
      - jupyter
      - jupyterlab
      - rsp_jupyter
      - rsconnect_jupyter
      - virtualenv
    executable: /opt/Python/{{ python_env_name }}/bin/pip

- name: enable rstudio jupyter extensions
  shell: "/opt/Python/{{ python_env_name }}/bin/jupyter-nbextension install --sys-prefix --py rsp_jupyter \
  && /opt/Python/{{ python_env_name }}/bin/jupyter-nbextension enable --sys-prefix --py rsp_jupyter \
  && /opt/Python/{{ python_env_name }}/bin/jupyter-nbextension install --sys-prefix --py rsconnect_jupyter \
  && /opt/Python/{{ python_env_name }}/bin/jupyter-nbextension enable --sys-prefix --py rsconnect_jupyter \
  && /opt/Python/{{ python_env_name }}/bin/jupyter-serverextension enable --sys-prefix --py rsconnect_jupyter"
  when: rstudio_pro is defined and rstudio_pro
