---
- name: add nginx deb repo
  lineinfile:
    path: /etc/apt/sources.list.d/nginx.list
    line: deb http://nginx.org/packages/mainline/ubuntu bionic nginx
    state: present
    create: yes

- name: add nginx deb source repo
  lineinfile:
    path: /etc/apt/sources.list.d/nginx.list
    line: deb-src http://nginx.org/packages/mainline/ubuntu bionic nginx
    state: present

- name: add nginx amplify deb repo
  lineinfile:
    path: /etc/apt/sources.list.d/nginx.list
    line: deb http://packages.amplify.nginx.com/ubuntu/ bionic amplify-agent
    state: present

- name: add nginx amplify deb source repo
  lineinfile:
    path: /etc/apt/sources.list.d/nginx.list
    line: deb-src http://packages.amplify.nginx.com/ubuntu/ bionic amplify-agent
    state: present
  
- name: add nginx repo signing key
  apt_key:
    url: http://nginx.org/keys/nginx_signing.key
    state: present

- name: install nginx
  apt:
    name: nginx
    update_cache: yes
    state: latest

- name: remove default site
  file:
    path: /etc/nginx/conf.d/default.conf
    state: absent
