---
- name: run base role
  become: yes
  include_role:
    name: python

- name: add python to system-wide PATH
  lineinfile:
    line: "PATH=/opt/Python/{{ python_env_name }}/bin:$PATH"
    path: /etc/profile.d/python{{ python_env_name }}.sh
    create: yes
