---
- name: run base role
  include_role:
    name: python

- name: install data science packages
  pip:
    name:
      - altair
      - cython
      - dask
      - gensim
      - keras
      - matplotlib
      - nltk
      - numpy
      - pandas
      - pillow
      - pyarrow
      - requests
      - scipy
      - scikit-image
      - scikit-learn
      - seaborn
      - spacy
      - sqlalchemy
      - statsmodels
      - tensorflow
      - xgboost
      - s3fs
    executable: /opt/Python/{{ python_env_name }}/bin/pip

- name: register jupyter kernel
  shell: "/opt/Python/{{ python_env_name }}/bin/python -m ipykernel install --name py{{ python_env_name }} --display-name 'Python {{ python_version }} (Data Science)'"
