- hosts: 127.0.0.1
  connection: local
  become: yes
  gather_facts: no
  roles:
    - workspace
    - web-server

  tasks:
    - name: download jupyterHub bootstrap script
      get_url:
        url: "{{ tljh_bootstrap_script }}"
        dest: /home/ansible
      register: bootstrap_download
  
    - name: run JupyterHub bootstrap script
      shell: "python3 {{ bootstrap_download.dest }}"

    - name: create exchange directory for nbgrader
      file:
        path: /srv/nbgrader/exchange
        state: directory
        group: jupyterhub-users
        mode: '0777'
          
    - name: disable idle culling
      shell: "tljh-config set services.cull.enabled False"

    - name: set jupyterlab as default
      shell: "tljh-config set user_environment.default_app jupyterlab"

    - name: reload hub configuration
      shell: "tljh-config reload hub"
      ignore_errors: yes

    - name: install r kernel
      shell: "/opt/tljh/user/bin/conda install --yes --quiet --channel r r-essentials"

    - name: install nbgrader
      shell: "/opt/tljh/user/bin/conda install --yes --quiet --channel conda-forge nbgrader \
              && /opt/tljh/user/bin/jupyter nbextension disable --sys-prefix create_assignment/main \
              && /opt/tljh/user/bin/jupyter nbextension disable --sys-prefix formgrader/main --section=tree \
              && /opt/tljh/user/bin/jupyter nbextension disable --sys-prefix course_list/main --section=tree"
