- hosts: postgresql
  gather_facts: no
  become: yes
  roles:
    - common
  vars:
    ansible_ssh_pipelining: true

  tasks:
    - name: install required library
      become: yes
      apt:
        name: python3-psycopg2
        state: present
        update_cache: yes

    - name: install postgresql
      become: yes
      apt: 
        name: postgresql
        state: present

    - name: add test database
      become: yes
      become_user: postgres
      postgresql_db:
        name: test_db
        state: present

    - name: add test user
      become: yes
      become_user: postgres
      no_log: true
      postgresql_user:
        db: test_db
        name: test_user
        password: test_password
        priv: "ALL/ALL"
        state: present
